// <auto-generated />
using GESTRF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GESTRF.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("HelpDesk.Models.Usuario", b =>
                {
          
                     b.Property<int>("UsuarioId").ValueGeneratedOnAdd().HasColumnType("int");
                     b.Property< string>("Nome").IsRequired().HasMaxLength(50).HasColumnType("varchar(50) CHARACTER SET utf8mb4");
                     b.Property< string>("Username").IsRequired().HasMaxLength(50).HasColumnType("varchar(50) CHARACTER SET utf8mb4"); 
                     b.Property<string>("Senha").IsRequired().HasMaxLength(50).HasColumnType("varchar(50) CHARACTER SET utf8mb4");
                     b.Property<string>("Email").IsRequired().HasMaxLength(50).HasColumnType("varchar(50) CHARACTER SET utf8mb4");
                     b.Property<string>("Perfil").IsRequired()  .HasMaxLength(50).HasColumnType("varchar(50) CHARACTER SET utf8mb4");           

                    
                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
